services:
  java:
    image: openjdk:8-jdk-alpine
  mongo:
    image: mongo
  spring_boot_mongo:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongo
    links:
      - java
version: "2"